server {
    listen 80;
    server_name 103.82.193.153; # Replace with your domain name if you have one

    # Serve static Frontend React files
    location / {
        root /var/www/stayhub/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Reverse proxy for API requests to Gateway API running on port 7010
    location /api/ {
        proxy_pass http://127.0.0.1:7010/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection keep-alive;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Reverse proxy for SignalR / WebSockets to Gateway API
    location /hubs/ {
        proxy_pass http://127.0.0.1:7010/hubs/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
