-- Expanded expert judgments for 40 synthetic eval profile keys (seed=42, n=100)
-- Run after StayHub_AiDb_Patch.sql and StayHub_AiDb_SeedEval.sql
USE StayHub_AiDb;
GO

DELETE FROM TourRelevanceJudgments WHERE JudgeId IN ('reviewer-batch', 'reviewer-01', 'reviewer-02', 'reviewer-03');
GO

-- 184 judgments across 40 profile query keys
INSERT INTO TourRelevanceJudgments (ProfileSignature, ProfileQueryKey, TourId, RelevanceGrade, Source, JudgeId, Notes, CreatedAt) VALUES
('exp-foreigner_da_lat_couple_', 'foreigner_da_lat_couple_beach', 1, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-foreigner_da_lat_couple_', 'foreigner_da_lat_couple_beach', 2, 3, 'expert', 'reviewer-batch', N'Primary tour in da lat', GETUTCDATE()),
('exp-foreigner_da_lat_couple_', 'foreigner_da_lat_couple_beach', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-foreigner_da_lat_couple_', 'foreigner_da_lat_couple_beach', 10, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-foreigner_da_lat_couple_', 'foreigner_da_lat_couple_beach', 12, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-foreigner_da_lat_couple_', 'foreigner_da_lat_couple_culture', 2, 3, 'expert', 'reviewer-batch', N'Primary tour in da lat', GETUTCDATE()),
('exp-foreigner_da_lat_couple_', 'foreigner_da_lat_couple_culture', 3, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-foreigner_da_lat_couple_', 'foreigner_da_lat_couple_culture', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-foreigner_da_lat_couple_', 'foreigner_da_lat_couple_culture', 7, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-foreigner_da_lat_couple_', 'foreigner_da_lat_couple_culture', 11, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-foreigner_da_lat_group_n', 'foreigner_da_lat_group_nature', 2, 3, 'expert', 'reviewer-batch', N'Primary tour in da lat', GETUTCDATE()),
('exp-foreigner_da_lat_group_n', 'foreigner_da_lat_group_nature', 6, 2, 'expert', 'reviewer-batch', N'Secondary fit for nature', GETUTCDATE()),
('exp-foreigner_da_lat_group_n', 'foreigner_da_lat_group_nature', 7, 2, 'expert', 'reviewer-batch', N'Secondary fit for nature', GETUTCDATE()),
('exp-foreigner_da_lat_group_r', 'foreigner_da_lat_group_relax', 1, 2, 'expert', 'reviewer-batch', N'Secondary fit for relax', GETUTCDATE()),
('exp-foreigner_da_lat_group_r', 'foreigner_da_lat_group_relax', 2, 3, 'expert', 'reviewer-batch', N'Primary tour in da lat', GETUTCDATE()),
('exp-foreigner_da_lat_group_r', 'foreigner_da_lat_group_relax', 4, 2, 'expert', 'reviewer-batch', N'Secondary fit for relax', GETUTCDATE()),
('exp-foreigner_da_lat_group_r', 'foreigner_da_lat_group_relax', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-foreigner_da_lat_group_r', 'foreigner_da_lat_group_relax', 10, 2, 'expert', 'reviewer-batch', N'Secondary fit for relax', GETUTCDATE()),
('exp-foreigner_da_nang_couple', 'foreigner_da_nang_couple_beach', 1, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-foreigner_da_nang_couple', 'foreigner_da_nang_couple_beach', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-foreigner_da_nang_couple', 'foreigner_da_nang_couple_beach', 8, 3, 'expert', 'reviewer-batch', N'Primary tour in da nang', GETUTCDATE()),
('exp-foreigner_da_nang_couple', 'foreigner_da_nang_couple_beach', 10, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-foreigner_da_nang_couple', 'foreigner_da_nang_couple_beach', 12, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-foreigner_da_nang_couple', 'foreigner_da_nang_couple_culture', 3, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-foreigner_da_nang_couple', 'foreigner_da_nang_couple_culture', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-foreigner_da_nang_couple', 'foreigner_da_nang_couple_culture', 7, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-foreigner_da_nang_couple', 'foreigner_da_nang_couple_culture', 8, 3, 'expert', 'reviewer-batch', N'Primary tour in da nang', GETUTCDATE()),
('exp-foreigner_da_nang_couple', 'foreigner_da_nang_couple_culture', 11, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-foreigner_da_nang_group_', 'foreigner_da_nang_group_nature', 2, 2, 'expert', 'reviewer-batch', N'Secondary fit for nature', GETUTCDATE()),
('exp-foreigner_da_nang_group_', 'foreigner_da_nang_group_nature', 6, 2, 'expert', 'reviewer-batch', N'Secondary fit for nature', GETUTCDATE()),
('exp-foreigner_da_nang_group_', 'foreigner_da_nang_group_nature', 7, 2, 'expert', 'reviewer-batch', N'Secondary fit for nature', GETUTCDATE()),
('exp-foreigner_da_nang_group_', 'foreigner_da_nang_group_nature', 8, 3, 'expert', 'reviewer-batch', N'Primary tour in da nang', GETUTCDATE()),
('exp-foreigner_da_nang_group_', 'foreigner_da_nang_group_relax', 1, 2, 'expert', 'reviewer-batch', N'Secondary fit for relax', GETUTCDATE()),
('exp-foreigner_da_nang_group_', 'foreigner_da_nang_group_relax', 4, 2, 'expert', 'reviewer-batch', N'Secondary fit for relax', GETUTCDATE()),
('exp-foreigner_da_nang_group_', 'foreigner_da_nang_group_relax', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-foreigner_da_nang_group_', 'foreigner_da_nang_group_relax', 8, 3, 'expert', 'reviewer-batch', N'Primary tour in da nang', GETUTCDATE()),
('exp-foreigner_da_nang_group_', 'foreigner_da_nang_group_relax', 10, 2, 'expert', 'reviewer-batch', N'Secondary fit for relax', GETUTCDATE()),
('exp-foreigner_ho_chi_minh_ci', 'foreigner_ho_chi_minh_city_couple_beach', 1, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-foreigner_ho_chi_minh_ci', 'foreigner_ho_chi_minh_city_couple_beach', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-foreigner_ho_chi_minh_ci', 'foreigner_ho_chi_minh_city_couple_beach', 9, 3, 'expert', 'reviewer-batch', N'Primary tour in ho chi minh city', GETUTCDATE()),
('exp-foreigner_ho_chi_minh_ci', 'foreigner_ho_chi_minh_city_couple_beach', 10, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-foreigner_ho_chi_minh_ci', 'foreigner_ho_chi_minh_city_couple_beach', 12, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-foreigner_ho_chi_minh_ci', 'foreigner_ho_chi_minh_city_couple_culture', 3, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-foreigner_ho_chi_minh_ci', 'foreigner_ho_chi_minh_city_couple_culture', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-foreigner_ho_chi_minh_ci', 'foreigner_ho_chi_minh_city_couple_culture', 7, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-foreigner_ho_chi_minh_ci', 'foreigner_ho_chi_minh_city_couple_culture', 9, 3, 'expert', 'reviewer-batch', N'Primary tour in ho chi minh city', GETUTCDATE()),
('exp-foreigner_ho_chi_minh_ci', 'foreigner_ho_chi_minh_city_couple_culture', 11, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-foreigner_ho_chi_minh_ci', 'foreigner_ho_chi_minh_city_group_nature', 2, 2, 'expert', 'reviewer-batch', N'Secondary fit for nature', GETUTCDATE()),
('exp-foreigner_ho_chi_minh_ci', 'foreigner_ho_chi_minh_city_group_nature', 6, 2, 'expert', 'reviewer-batch', N'Secondary fit for nature', GETUTCDATE()),
('exp-foreigner_ho_chi_minh_ci', 'foreigner_ho_chi_minh_city_group_nature', 7, 2, 'expert', 'reviewer-batch', N'Secondary fit for nature', GETUTCDATE()),
('exp-foreigner_ho_chi_minh_ci', 'foreigner_ho_chi_minh_city_group_nature', 9, 3, 'expert', 'reviewer-batch', N'Primary tour in ho chi minh city', GETUTCDATE()),
('exp-foreigner_ho_chi_minh_ci', 'foreigner_ho_chi_minh_city_group_relax', 1, 2, 'expert', 'reviewer-batch', N'Secondary fit for relax', GETUTCDATE()),
('exp-foreigner_ho_chi_minh_ci', 'foreigner_ho_chi_minh_city_group_relax', 4, 2, 'expert', 'reviewer-batch', N'Secondary fit for relax', GETUTCDATE()),
('exp-foreigner_ho_chi_minh_ci', 'foreigner_ho_chi_minh_city_group_relax', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-foreigner_ho_chi_minh_ci', 'foreigner_ho_chi_minh_city_group_relax', 9, 3, 'expert', 'reviewer-batch', N'Primary tour in ho chi minh city', GETUTCDATE()),
('exp-foreigner_ho_chi_minh_ci', 'foreigner_ho_chi_minh_city_group_relax', 10, 2, 'expert', 'reviewer-batch', N'Secondary fit for relax', GETUTCDATE()),
('exp-foreigner_phu_quoc_coupl', 'foreigner_phu_quoc_couple_beach', 1, 3, 'expert', 'reviewer-batch', N'Primary tour in phu quoc', GETUTCDATE()),
('exp-foreigner_phu_quoc_coupl', 'foreigner_phu_quoc_couple_beach', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-foreigner_phu_quoc_coupl', 'foreigner_phu_quoc_couple_beach', 10, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-foreigner_phu_quoc_coupl', 'foreigner_phu_quoc_couple_beach', 12, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-foreigner_phu_quoc_coupl', 'foreigner_phu_quoc_couple_culture', 1, 3, 'expert', 'reviewer-batch', N'Primary tour in phu quoc', GETUTCDATE()),
('exp-foreigner_phu_quoc_coupl', 'foreigner_phu_quoc_couple_culture', 3, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-foreigner_phu_quoc_coupl', 'foreigner_phu_quoc_couple_culture', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-foreigner_phu_quoc_coupl', 'foreigner_phu_quoc_couple_culture', 7, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-foreigner_phu_quoc_coupl', 'foreigner_phu_quoc_couple_culture', 11, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-foreigner_phu_quoc_group', 'foreigner_phu_quoc_group_nature', 1, 3, 'expert', 'reviewer-batch', N'Primary tour in phu quoc', GETUTCDATE()),
('exp-foreigner_phu_quoc_group', 'foreigner_phu_quoc_group_nature', 2, 2, 'expert', 'reviewer-batch', N'Secondary fit for nature', GETUTCDATE()),
('exp-foreigner_phu_quoc_group', 'foreigner_phu_quoc_group_nature', 6, 2, 'expert', 'reviewer-batch', N'Secondary fit for nature', GETUTCDATE()),
('exp-foreigner_phu_quoc_group', 'foreigner_phu_quoc_group_nature', 7, 2, 'expert', 'reviewer-batch', N'Secondary fit for nature', GETUTCDATE()),
('exp-foreigner_phu_quoc_group', 'foreigner_phu_quoc_group_relax', 1, 3, 'expert', 'reviewer-batch', N'Primary tour in phu quoc', GETUTCDATE()),
('exp-foreigner_phu_quoc_group', 'foreigner_phu_quoc_group_relax', 4, 2, 'expert', 'reviewer-batch', N'Secondary fit for relax', GETUTCDATE()),
('exp-foreigner_phu_quoc_group', 'foreigner_phu_quoc_group_relax', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-foreigner_phu_quoc_group', 'foreigner_phu_quoc_group_relax', 10, 2, 'expert', 'reviewer-batch', N'Secondary fit for relax', GETUTCDATE()),
('exp-foreigner_sapa_couple_be', 'foreigner_sapa_couple_beach', 1, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-foreigner_sapa_couple_be', 'foreigner_sapa_couple_beach', 6, 3, 'expert', 'reviewer-batch', N'Primary tour in sapa', GETUTCDATE()),
('exp-foreigner_sapa_couple_be', 'foreigner_sapa_couple_beach', 9, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-foreigner_sapa_couple_be', 'foreigner_sapa_couple_beach', 10, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-foreigner_sapa_couple_be', 'foreigner_sapa_couple_beach', 12, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-foreigner_sapa_couple_cu', 'foreigner_sapa_couple_culture', 3, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-foreigner_sapa_couple_cu', 'foreigner_sapa_couple_culture', 6, 3, 'expert', 'reviewer-batch', N'Primary tour in sapa', GETUTCDATE()),
('exp-foreigner_sapa_couple_cu', 'foreigner_sapa_couple_culture', 7, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-foreigner_sapa_couple_cu', 'foreigner_sapa_couple_culture', 9, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-foreigner_sapa_couple_cu', 'foreigner_sapa_couple_culture', 11, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-foreigner_sapa_group_nat', 'foreigner_sapa_group_nature', 2, 2, 'expert', 'reviewer-batch', N'Secondary fit for nature', GETUTCDATE()),
('exp-foreigner_sapa_group_nat', 'foreigner_sapa_group_nature', 6, 3, 'expert', 'reviewer-batch', N'Primary tour in sapa', GETUTCDATE()),
('exp-foreigner_sapa_group_nat', 'foreigner_sapa_group_nature', 7, 2, 'expert', 'reviewer-batch', N'Secondary fit for nature', GETUTCDATE()),
('exp-foreigner_sapa_group_nat', 'foreigner_sapa_group_nature', 9, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-foreigner_sapa_group_rel', 'foreigner_sapa_group_relax', 1, 2, 'expert', 'reviewer-batch', N'Secondary fit for relax', GETUTCDATE()),
('exp-foreigner_sapa_group_rel', 'foreigner_sapa_group_relax', 4, 2, 'expert', 'reviewer-batch', N'Secondary fit for relax', GETUTCDATE()),
('exp-foreigner_sapa_group_rel', 'foreigner_sapa_group_relax', 6, 3, 'expert', 'reviewer-batch', N'Primary tour in sapa', GETUTCDATE()),
('exp-foreigner_sapa_group_rel', 'foreigner_sapa_group_relax', 9, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-foreigner_sapa_group_rel', 'foreigner_sapa_group_relax', 10, 2, 'expert', 'reviewer-batch', N'Secondary fit for relax', GETUTCDATE()),
('exp-vietnamese_can_tho_famil', 'vietnamese_can_tho_family_culture', 3, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-vietnamese_can_tho_famil', 'vietnamese_can_tho_family_culture', 5, 3, 'expert', 'reviewer-batch', N'Primary tour in can tho', GETUTCDATE()),
('exp-vietnamese_can_tho_famil', 'vietnamese_can_tho_family_culture', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-vietnamese_can_tho_famil', 'vietnamese_can_tho_family_culture', 7, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-vietnamese_can_tho_famil', 'vietnamese_can_tho_family_culture', 11, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-vietnamese_can_tho_famil', 'vietnamese_can_tho_family_river', 3, 2, 'expert', 'reviewer-batch', N'Secondary fit for river', GETUTCDATE()),
('exp-vietnamese_can_tho_famil', 'vietnamese_can_tho_family_river', 5, 3, 'expert', 'reviewer-batch', N'Primary tour in can tho', GETUTCDATE()),
('exp-vietnamese_can_tho_famil', 'vietnamese_can_tho_family_river', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-vietnamese_can_tho_famil', 'vietnamese_can_tho_family_river', 7, 2, 'expert', 'reviewer-batch', N'Secondary fit for river', GETUTCDATE()),
('exp-vietnamese_can_tho_solo_', 'vietnamese_can_tho_solo_beach', 1, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-vietnamese_can_tho_solo_', 'vietnamese_can_tho_solo_beach', 5, 3, 'expert', 'reviewer-batch', N'Primary tour in can tho', GETUTCDATE()),
('exp-vietnamese_can_tho_solo_', 'vietnamese_can_tho_solo_beach', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-vietnamese_can_tho_solo_', 'vietnamese_can_tho_solo_beach', 10, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-vietnamese_can_tho_solo_', 'vietnamese_can_tho_solo_beach', 12, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-vietnamese_can_tho_solo_', 'vietnamese_can_tho_solo_city', 5, 3, 'expert', 'reviewer-batch', N'Primary tour in can tho', GETUTCDATE()),
('exp-vietnamese_can_tho_solo_', 'vietnamese_can_tho_solo_city', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-vietnamese_can_tho_solo_', 'vietnamese_can_tho_solo_city', 8, 2, 'expert', 'reviewer-batch', N'Secondary fit for city', GETUTCDATE()),
('exp-vietnamese_can_tho_solo_', 'vietnamese_can_tho_solo_city', 9, 2, 'expert', 'reviewer-batch', N'Secondary fit for city', GETUTCDATE()),
('exp-vietnamese_can_tho_solo_', 'vietnamese_can_tho_solo_city', 11, 2, 'expert', 'reviewer-batch', N'Secondary fit for city', GETUTCDATE()),
('exp-vietnamese_ha_noi_family', 'vietnamese_ha_noi_family_culture', 3, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-vietnamese_ha_noi_family', 'vietnamese_ha_noi_family_culture', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-vietnamese_ha_noi_family', 'vietnamese_ha_noi_family_culture', 7, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-vietnamese_ha_noi_family', 'vietnamese_ha_noi_family_culture', 11, 3, 'expert', 'reviewer-batch', N'Primary tour in ha noi', GETUTCDATE()),
('exp-vietnamese_ha_noi_family', 'vietnamese_ha_noi_family_river', 3, 2, 'expert', 'reviewer-batch', N'Secondary fit for river', GETUTCDATE()),
('exp-vietnamese_ha_noi_family', 'vietnamese_ha_noi_family_river', 5, 2, 'expert', 'reviewer-batch', N'Secondary fit for river', GETUTCDATE()),
('exp-vietnamese_ha_noi_family', 'vietnamese_ha_noi_family_river', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-vietnamese_ha_noi_family', 'vietnamese_ha_noi_family_river', 7, 2, 'expert', 'reviewer-batch', N'Secondary fit for river', GETUTCDATE()),
('exp-vietnamese_ha_noi_family', 'vietnamese_ha_noi_family_river', 11, 3, 'expert', 'reviewer-batch', N'Primary tour in ha noi', GETUTCDATE()),
('exp-vietnamese_ha_noi_solo_b', 'vietnamese_ha_noi_solo_beach', 1, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-vietnamese_ha_noi_solo_b', 'vietnamese_ha_noi_solo_beach', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-vietnamese_ha_noi_solo_b', 'vietnamese_ha_noi_solo_beach', 10, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-vietnamese_ha_noi_solo_b', 'vietnamese_ha_noi_solo_beach', 11, 3, 'expert', 'reviewer-batch', N'Primary tour in ha noi', GETUTCDATE()),
('exp-vietnamese_ha_noi_solo_b', 'vietnamese_ha_noi_solo_beach', 12, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-vietnamese_ha_noi_solo_c', 'vietnamese_ha_noi_solo_city', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-vietnamese_ha_noi_solo_c', 'vietnamese_ha_noi_solo_city', 8, 2, 'expert', 'reviewer-batch', N'Secondary fit for city', GETUTCDATE()),
('exp-vietnamese_ha_noi_solo_c', 'vietnamese_ha_noi_solo_city', 9, 2, 'expert', 'reviewer-batch', N'Secondary fit for city', GETUTCDATE()),
('exp-vietnamese_ha_noi_solo_c', 'vietnamese_ha_noi_solo_city', 11, 3, 'expert', 'reviewer-batch', N'Primary tour in ha noi', GETUTCDATE()),
('exp-vietnamese_hoi_an_family', 'vietnamese_hoi_an_family_culture', 3, 3, 'expert', 'reviewer-batch', N'Primary tour in hoi an', GETUTCDATE()),
('exp-vietnamese_hoi_an_family', 'vietnamese_hoi_an_family_culture', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-vietnamese_hoi_an_family', 'vietnamese_hoi_an_family_culture', 7, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-vietnamese_hoi_an_family', 'vietnamese_hoi_an_family_culture', 11, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-vietnamese_hoi_an_family', 'vietnamese_hoi_an_family_river', 3, 3, 'expert', 'reviewer-batch', N'Primary tour in hoi an', GETUTCDATE()),
('exp-vietnamese_hoi_an_family', 'vietnamese_hoi_an_family_river', 5, 2, 'expert', 'reviewer-batch', N'Secondary fit for river', GETUTCDATE()),
('exp-vietnamese_hoi_an_family', 'vietnamese_hoi_an_family_river', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-vietnamese_hoi_an_family', 'vietnamese_hoi_an_family_river', 7, 2, 'expert', 'reviewer-batch', N'Secondary fit for river', GETUTCDATE()),
('exp-vietnamese_hoi_an_solo_b', 'vietnamese_hoi_an_solo_beach', 1, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-vietnamese_hoi_an_solo_b', 'vietnamese_hoi_an_solo_beach', 3, 3, 'expert', 'reviewer-batch', N'Primary tour in hoi an', GETUTCDATE()),
('exp-vietnamese_hoi_an_solo_b', 'vietnamese_hoi_an_solo_beach', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-vietnamese_hoi_an_solo_b', 'vietnamese_hoi_an_solo_beach', 10, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-vietnamese_hoi_an_solo_b', 'vietnamese_hoi_an_solo_beach', 12, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-vietnamese_hoi_an_solo_c', 'vietnamese_hoi_an_solo_city', 3, 3, 'expert', 'reviewer-batch', N'Primary tour in hoi an', GETUTCDATE()),
('exp-vietnamese_hoi_an_solo_c', 'vietnamese_hoi_an_solo_city', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-vietnamese_hoi_an_solo_c', 'vietnamese_hoi_an_solo_city', 8, 2, 'expert', 'reviewer-batch', N'Secondary fit for city', GETUTCDATE()),
('exp-vietnamese_hoi_an_solo_c', 'vietnamese_hoi_an_solo_city', 9, 2, 'expert', 'reviewer-batch', N'Secondary fit for city', GETUTCDATE()),
('exp-vietnamese_hoi_an_solo_c', 'vietnamese_hoi_an_solo_city', 11, 2, 'expert', 'reviewer-batch', N'Secondary fit for city', GETUTCDATE()),
('exp-vietnamese_nha_trang_fam', 'vietnamese_nha_trang_family_culture', 3, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-vietnamese_nha_trang_fam', 'vietnamese_nha_trang_family_culture', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-vietnamese_nha_trang_fam', 'vietnamese_nha_trang_family_culture', 7, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-vietnamese_nha_trang_fam', 'vietnamese_nha_trang_family_culture', 11, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-vietnamese_nha_trang_fam', 'vietnamese_nha_trang_family_culture', 12, 3, 'expert', 'reviewer-batch', N'Primary tour in nha trang', GETUTCDATE()),
('exp-vietnamese_nha_trang_fam', 'vietnamese_nha_trang_family_river', 3, 2, 'expert', 'reviewer-batch', N'Secondary fit for river', GETUTCDATE()),
('exp-vietnamese_nha_trang_fam', 'vietnamese_nha_trang_family_river', 5, 2, 'expert', 'reviewer-batch', N'Secondary fit for river', GETUTCDATE()),
('exp-vietnamese_nha_trang_fam', 'vietnamese_nha_trang_family_river', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-vietnamese_nha_trang_fam', 'vietnamese_nha_trang_family_river', 7, 2, 'expert', 'reviewer-batch', N'Secondary fit for river', GETUTCDATE()),
('exp-vietnamese_nha_trang_fam', 'vietnamese_nha_trang_family_river', 12, 3, 'expert', 'reviewer-batch', N'Primary tour in nha trang', GETUTCDATE()),
('exp-vietnamese_nha_trang_sol', 'vietnamese_nha_trang_solo_beach', 1, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-vietnamese_nha_trang_sol', 'vietnamese_nha_trang_solo_beach', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-vietnamese_nha_trang_sol', 'vietnamese_nha_trang_solo_beach', 10, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-vietnamese_nha_trang_sol', 'vietnamese_nha_trang_solo_beach', 12, 3, 'expert', 'reviewer-batch', N'Primary tour in nha trang', GETUTCDATE()),
('exp-vietnamese_nha_trang_sol', 'vietnamese_nha_trang_solo_city', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-vietnamese_nha_trang_sol', 'vietnamese_nha_trang_solo_city', 8, 2, 'expert', 'reviewer-batch', N'Secondary fit for city', GETUTCDATE()),
('exp-vietnamese_nha_trang_sol', 'vietnamese_nha_trang_solo_city', 9, 2, 'expert', 'reviewer-batch', N'Secondary fit for city', GETUTCDATE()),
('exp-vietnamese_nha_trang_sol', 'vietnamese_nha_trang_solo_city', 11, 2, 'expert', 'reviewer-batch', N'Secondary fit for city', GETUTCDATE()),
('exp-vietnamese_nha_trang_sol', 'vietnamese_nha_trang_solo_city', 12, 3, 'expert', 'reviewer-batch', N'Primary tour in nha trang', GETUTCDATE()),
('exp-vietnamese_ninh_binh_fam', 'vietnamese_ninh_binh_family_culture', 3, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-vietnamese_ninh_binh_fam', 'vietnamese_ninh_binh_family_culture', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-vietnamese_ninh_binh_fam', 'vietnamese_ninh_binh_family_culture', 7, 3, 'expert', 'reviewer-batch', N'Primary tour in ninh binh', GETUTCDATE()),
('exp-vietnamese_ninh_binh_fam', 'vietnamese_ninh_binh_family_culture', 11, 2, 'expert', 'reviewer-batch', N'Secondary fit for culture', GETUTCDATE()),
('exp-vietnamese_ninh_binh_fam', 'vietnamese_ninh_binh_family_river', 3, 2, 'expert', 'reviewer-batch', N'Secondary fit for river', GETUTCDATE()),
('exp-vietnamese_ninh_binh_fam', 'vietnamese_ninh_binh_family_river', 5, 2, 'expert', 'reviewer-batch', N'Secondary fit for river', GETUTCDATE()),
('exp-vietnamese_ninh_binh_fam', 'vietnamese_ninh_binh_family_river', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-vietnamese_ninh_binh_fam', 'vietnamese_ninh_binh_family_river', 7, 3, 'expert', 'reviewer-batch', N'Primary tour in ninh binh', GETUTCDATE()),
('exp-vietnamese_ninh_binh_sol', 'vietnamese_ninh_binh_solo_beach', 1, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-vietnamese_ninh_binh_sol', 'vietnamese_ninh_binh_solo_beach', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-vietnamese_ninh_binh_sol', 'vietnamese_ninh_binh_solo_beach', 7, 3, 'expert', 'reviewer-batch', N'Primary tour in ninh binh', GETUTCDATE()),
('exp-vietnamese_ninh_binh_sol', 'vietnamese_ninh_binh_solo_beach', 10, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-vietnamese_ninh_binh_sol', 'vietnamese_ninh_binh_solo_beach', 12, 2, 'expert', 'reviewer-batch', N'Secondary fit for beach', GETUTCDATE()),
('exp-vietnamese_ninh_binh_sol', 'vietnamese_ninh_binh_solo_city', 6, 0, 'expert', 'reviewer-batch', N'Irrelevant destination', GETUTCDATE()),
('exp-vietnamese_ninh_binh_sol', 'vietnamese_ninh_binh_solo_city', 7, 3, 'expert', 'reviewer-batch', N'Primary tour in ninh binh', GETUTCDATE()),
('exp-vietnamese_ninh_binh_sol', 'vietnamese_ninh_binh_solo_city', 8, 2, 'expert', 'reviewer-batch', N'Secondary fit for city', GETUTCDATE()),
('exp-vietnamese_ninh_binh_sol', 'vietnamese_ninh_binh_solo_city', 9, 2, 'expert', 'reviewer-batch', N'Secondary fit for city', GETUTCDATE()),
('exp-vietnamese_ninh_binh_sol', 'vietnamese_ninh_binh_solo_city', 11, 2, 'expert', 'reviewer-batch', N'Secondary fit for city', GETUTCDATE());
GO

PRINT 'Expert judgments batch import completed.';
GO