using AIAPI.DTOs;
using AIAPI.ML;
using AIAPI.Models;
using AIAPI.Models.Catalog;
using AIAPI.Recommender;
using AIAPI.Services;
using Microsoft.EntityFrameworkCore;

namespace AIAPI.Services.Implements;

public class UserStudyService : IUserStudyService
{
    private const string CafhrKey = AggregationStrategies.CafhrFair;

    private readonly StayHubAiDbContext _db;
    private readonly ICatalogStore _catalogStore;
    private readonly IMlModelRegistry _modelRegistry;
    private readonly TourRanker _tourRanker;

    public UserStudyService(
        StayHubAiDbContext db,
        ICatalogStore catalogStore,
        IMlModelRegistry modelRegistry,
        TourRanker tourRanker)
    {
        _db = db;
        _catalogStore = catalogStore;
        _modelRegistry = modelRegistry;
        _tourRanker = tourRanker;
    }

    public UserStudyProtocolDTO GetProtocol() => new()
    {
        ProtocolVersion = ScoringModelSpec.ModelVersion,
        Title = "Within-subjects comparison: FCAHR vs baselines (blind lists A/B)",
        Objective =
            "Measure perceived fairness, group fairness, satisfaction, and booking intent " +
            "when participants compare recommendation lists generated by FCAHR and baseline strategies.",
        TargetParticipants = EvaluationDataSpec.UserStudyTargetParticipants,
        TargetGroups = EvaluationDataSpec.UserStudyTargetGroups,
        ScenarioCount = UserStudyScenarioCatalog.ScenarioCount,
        ToursPerList = UserStudyScenarioCatalog.ToursPerList,
        EstimatedMinutes = 15,
        ComparisonPairs =
        [
            "cafhr_fair_vs_mean_utility",
            "cafhr_fair_vs_content_only"
        ],
        Instructions =
        [
            "Mỗi scenario mô tả một nhóm du lịch cụ thể (companion, sở thích, thành viên đặc biệt).",
            "Xem danh sách tour A và B (không biết thuật toán nào tạo ra).",
            "Đánh giá thang Likert 1–7 cho từng danh sách: công bằng cá nhân, công bằng cho cả nhóm, hài lòng, khả năng đặt tour.",
            "Chọn danh sách bạn thích hơn (A, B, hoặc none).",
            $"Hoàn thành {UserStudyScenarioCatalog.ScenarioCount} scenario (1 scenario = 1 nhóm du lịch); mỗi sessionId đại diện một người hoặc nhóm."
        ],
        Scales =
        [
            new LikertScaleDefinitionDTO
            {
                Key = "fairness",
                Label = "Mức công bằng với bạn cá nhân",
                Min = 1, Max = 7,
                MinLabel = "Rất không công bằng",
                MaxLabel = "Rất công bằng"
            },
            new LikertScaleDefinitionDTO
            {
                Key = "group_fairness",
                Label = "Mức công bằng cho cả nhóm/couple/gia đình",
                Min = 1, Max = 7,
                MinLabel = "Rất không công bằng",
                MaxLabel = "Rất công bằng"
            },
            new LikertScaleDefinitionDTO
            {
                Key = "satisfaction",
                Label = "Mức hài lòng với danh sách gợi ý",
                Min = 1, Max = 7,
                MinLabel = "Rất không hài lòng",
                MaxLabel = "Rất hài lòng"
            },
            new LikertScaleDefinitionDTO
            {
                Key = "would_book",
                Label = "Khả năng bạn sẽ đặt một tour trong danh sách",
                Min = 1, Max = 7,
                MinLabel = "Chắc chắn không",
                MaxLabel = "Chắc chắn có"
            }
        ],
        PowerAnalysis = UserStudyPowerAnalysis.Describe()
    };

    public IReadOnlyList<UserStudyScenarioDTO> GetScenarios()
    {
        return Enumerable.Range(0, UserStudyScenarioCatalog.ScenarioCount)
            .Select(UserStudyScenarioCatalog.Describe)
            .ToList();
    }

    public async Task<UserStudyComparisonDTO> GetComparisonAsync(
        string sessionId,
        int scenarioId,
        CancellationToken cancellationToken = default)
    {
        EnsureReady();
        ValidateScenarioId(scenarioId);

        if (string.IsNullOrWhiteSpace(sessionId) || sessionId.Length < 8)
        {
            throw new InvalidOperationException("SessionId must be at least 8 characters (anonymous participant id).");
        }

        var assignment = await GetOrCreateAssignmentAsync(sessionId, scenarioId, cancellationToken);
        var profile = UserStudyScenarioCatalog.BuildProfile(scenarioId);
        var semantic = BuildSemanticScores(profile);

        var (proposed, baseline) = UserStudyScenarioCatalog.GetStrategies(scenarioId);
        var proposedTours = RankBlind(profile, semantic, proposed);
        var baselineTours = RankBlind(profile, semantic, baseline);

        var swap = ShouldSwapLists(sessionId, scenarioId);
        var listAStrategy = swap ? baseline : proposed;
        var listBStrategy = swap ? proposed : baseline;
        var listATours = swap ? baselineTours : proposedTours;
        var listBTours = swap ? proposedTours : baselineTours;

        if (assignment.StrategyForListA != listAStrategy || assignment.StrategyForListB != listBStrategy)
        {
            assignment.StrategyForListA = listAStrategy;
            assignment.StrategyForListB = listBStrategy;
            await _db.SaveChangesAsync(cancellationToken);
        }

        var alreadySubmitted = await _db.UserStudyResponses
            .AnyAsync(r => r.SessionId == sessionId && r.ScenarioId == scenarioId, cancellationToken);

        return new UserStudyComparisonDTO
        {
            AssignmentId = assignment.Id,
            ScenarioId = scenarioId,
            SessionId = sessionId,
            Scenario = UserStudyScenarioCatalog.Describe(scenarioId),
            ListA = new UserStudyBlindListDTO { Label = "A", Tours = listATours },
            ListB = new UserStudyBlindListDTO { Label = "B", Tours = listBTours },
            AlreadySubmitted = alreadySubmitted
        };
    }

    public async Task<SubmitUserStudyResponseResultDTO> SubmitResponseAsync(
        SubmitUserStudyResponseDTO request,
        CancellationToken cancellationToken = default)
    {
        var assignment = await _db.UserStudyAssignments
            .FirstOrDefaultAsync(a => a.Id == request.AssignmentId, cancellationToken)
            ?? throw new InvalidOperationException("Assignment not found.");

        if (!string.Equals(assignment.SessionId, request.SessionId, StringComparison.Ordinal))
        {
            throw new InvalidOperationException("SessionId does not match assignment.");
        }

        var exists = await _db.UserStudyResponses
            .AnyAsync(r => r.SessionId == request.SessionId && r.ScenarioId == assignment.ScenarioId, cancellationToken);

        if (exists)
        {
            throw new InvalidOperationException("Response already submitted for this scenario.");
        }

        var preferred = request.PreferredList.Trim().ToUpperInvariant();
        if (preferred is not ("A" or "B" or "NONE"))
        {
            throw new InvalidOperationException("PreferredList must be A, B, or none.");
        }

        var entity = new UserStudyResponse
        {
            AssignmentId = assignment.Id,
            SessionId = request.SessionId,
            ScenarioId = assignment.ScenarioId,
            PreferredList = preferred,
            FairnessListA = request.FairnessListA,
            FairnessListB = request.FairnessListB,
            SatisfactionListA = request.SatisfactionListA,
            SatisfactionListB = request.SatisfactionListB,
            GroupFairnessListA = request.GroupFairnessListA,
            GroupFairnessListB = request.GroupFairnessListB,
            WouldBookListA = request.WouldBookListA,
            WouldBookListB = request.WouldBookListB,
            AgeGroup = request.AgeGroup,
            TravelExperience = request.TravelExperience,
            OpenComment = request.OpenComment,
            ResponseSource = "human",
            CreatedAt = DateTime.UtcNow
        };

        _db.UserStudyResponses.Add(entity);
        await _db.SaveChangesAsync(cancellationToken);

        return new SubmitUserStudyResponseResultDTO
        {
            ResponseId = entity.Id,
            Message = "User study response recorded."
        };
    }

    public async Task<UserStudySummaryDTO> GetSummaryAsync(CancellationToken cancellationToken = default)
    {
        var responses = await _db.UserStudyResponses
            .AsNoTracking()
            .Include(r => r.Assignment)
            .Where(r => r.ResponseSource == "human")
            .ToListAsync(cancellationToken);

        var uniqueParticipants = responses.Select(r => r.SessionId).Distinct().Count();
        var target = EvaluationDataSpec.UserStudyTargetParticipants;
        var scenariosPerParticipant = UserStudyScenarioCatalog.ScenarioCount;
        var completionRate = target == 0
            ? 0f
            : Math.Min(1f, uniqueParticipants / (float)target);

        var comparisonStats = responses
            .GroupBy(r => r.Assignment.ComparisonPair)
            .Select(g => BuildComparisonStats(g.Key, g.ToList()))
            .OrderBy(x => x.ComparisonPair)
            .ToList();

        var fcahrWins = 0;
        var totalPrefs = 0;
        var fairnessDeltas = new List<float>();
        var satisfactionDeltas = new List<float>();
        var groupFairnessDeltas = new List<float>();

        foreach (var r in responses)
        {
            var fcahrOnA = r.Assignment.StrategyForListA == CafhrKey;
            var fcahrOnB = r.Assignment.StrategyForListB == CafhrKey;

            if (r.PreferredList == "A" && fcahrOnA)
            {
                fcahrWins++;
                totalPrefs++;
            }
            else if (r.PreferredList == "B" && fcahrOnB)
            {
                fcahrWins++;
                totalPrefs++;
            }
            else if (r.PreferredList is "A" or "B")
            {
                totalPrefs++;
            }

            fairnessDeltas.Add(FcahrMetricDelta(r, fcahrOnA, fcahrOnB, r.FairnessListA, r.FairnessListB));
            satisfactionDeltas.Add(FcahrMetricDelta(r, fcahrOnA, fcahrOnB, r.SatisfactionListA, r.SatisfactionListB));
            groupFairnessDeltas.Add(FcahrMetricDelta(r, fcahrOnA, fcahrOnB, r.GroupFairnessListA, r.GroupFairnessListB));
        }

        var groupTypeStats = responses
            .GroupBy(r => UserStudyScenarioCatalog.GroupTypes[r.ScenarioId])
            .Select(g => BuildGroupTypeStats(g.Key, g.ToList()))
            .OrderBy(x => x.GroupType)
            .ToList();

        return new UserStudySummaryDTO
        {
            ProtocolVersion = ScoringModelSpec.ModelVersion,
            TotalResponses = responses.Count,
            UniqueParticipants = uniqueParticipants,
            TargetParticipants = target,
            TargetScenariosPerParticipant = scenariosPerParticipant,
            CompletionRate = completionRate,
            ComparisonStats = comparisonStats,
            GroupTypeStats = groupTypeStats,
            FcahrAggregate = new UserStudyFcahrAggregateDTO
            {
                OverallPreferenceRate = totalPrefs == 0 ? 0f : fcahrWins / (float)totalPrefs,
                MeanFairnessAdvantage = Mean(fairnessDeltas),
                MeanSatisfactionAdvantage = Mean(satisfactionDeltas),
                MeanGroupFairnessAdvantage = Mean(groupFairnessDeltas)
            },
            PowerAnalysis = UserStudyPowerAnalysis.Describe(),
            GeneratedAt = DateTime.UtcNow
        };
    }

    private UserStudyGroupTypeStatsDTO BuildGroupTypeStats(string groupType, List<UserStudyResponse> rows)
    {
        var fcahrWins = 0;
        var prefCount = 0;
        var groupFairnessDeltas = new List<float>();

        foreach (var r in rows)
        {
            var fcahrOnA = r.Assignment.StrategyForListA == CafhrKey;
            var fcahrOnB = r.Assignment.StrategyForListB == CafhrKey;

            if (r.PreferredList == "A" && fcahrOnA)
            {
                fcahrWins++;
                prefCount++;
            }
            else if (r.PreferredList == "B" && fcahrOnB)
            {
                fcahrWins++;
                prefCount++;
            }
            else if (r.PreferredList is "A" or "B")
            {
                prefCount++;
            }

            groupFairnessDeltas.Add(
                FcahrMetricDelta(r, fcahrOnA, fcahrOnB, r.GroupFairnessListA, r.GroupFairnessListB));
        }

        return new UserStudyGroupTypeStatsDTO
        {
            GroupType = groupType,
            ResponseCount = rows.Count,
            FcahrPreferenceRate = prefCount == 0 ? 0f : fcahrWins / (float)prefCount,
            MeanGroupFairnessAdvantage = Mean(groupFairnessDeltas)
        };
    }

    private UserStudyComparisonStatsDTO BuildComparisonStats(string pair, List<UserStudyResponse> rows)
    {
        var fcahrWins = 0;
        var prefCount = 0;
        var fairnessDeltas = new List<float>();
        var satisfactionDeltas = new List<float>();
        var groupFairnessDeltas = new List<float>();
        var signDeltas = new List<float>();

        foreach (var r in rows)
        {
            var fcahrOnA = r.Assignment.StrategyForListA == CafhrKey;
            var fcahrOnB = r.Assignment.StrategyForListB == CafhrKey;

            if (r.PreferredList == "A" && fcahrOnA)
            {
                fcahrWins++;
                prefCount++;
                signDeltas.Add(1f);
            }
            else if (r.PreferredList == "B" && fcahrOnB)
            {
                fcahrWins++;
                prefCount++;
                signDeltas.Add(1f);
            }
            else if (r.PreferredList == "A" && fcahrOnB)
            {
                prefCount++;
                signDeltas.Add(-1f);
            }
            else if (r.PreferredList == "B" && fcahrOnA)
            {
                prefCount++;
                signDeltas.Add(-1f);
            }

            fairnessDeltas.Add(FcahrMetricDelta(r, fcahrOnA, fcahrOnB, r.FairnessListA, r.FairnessListB));
            satisfactionDeltas.Add(FcahrMetricDelta(r, fcahrOnA, fcahrOnB, r.SatisfactionListA, r.SatisfactionListB));
            groupFairnessDeltas.Add(FcahrMetricDelta(r, fcahrOnA, fcahrOnB, r.GroupFairnessListA, r.GroupFairnessListB));
        }

        return new UserStudyComparisonStatsDTO
        {
            ComparisonPair = pair,
            ResponseCount = rows.Count,
            FcahrPreferenceRate = prefCount == 0 ? 0f : fcahrWins / (float)prefCount,
            MeanFairnessDelta = Mean(fairnessDeltas),
            MeanSatisfactionDelta = Mean(satisfactionDeltas),
            MeanGroupFairnessDelta = Mean(groupFairnessDeltas),
            PreferenceSignTestPApprox = EvaluationMetricsCalculator.ApproximatePairedPValue(signDeltas)
        };
    }

    private static float FcahrMetricDelta(
        UserStudyResponse r,
        bool fcahrOnA,
        bool fcahrOnB,
        int scoreA,
        int scoreB)
    {
        if (fcahrOnA && !fcahrOnB)
        {
            return scoreA - scoreB;
        }

        if (fcahrOnB && !fcahrOnA)
        {
            return scoreB - scoreA;
        }

        return 0f;
    }

    private static float Mean(IReadOnlyList<float> values) =>
        values.Count == 0 ? 0f : values.Average();

    private async Task<UserStudyAssignment> GetOrCreateAssignmentAsync(
        string sessionId,
        int scenarioId,
        CancellationToken cancellationToken)
    {
        var existing = await _db.UserStudyAssignments
            .FirstOrDefaultAsync(a => a.SessionId == sessionId && a.ScenarioId == scenarioId, cancellationToken);

        if (existing != null)
        {
            return existing;
        }

        var (proposed, baseline) = UserStudyScenarioCatalog.GetStrategies(scenarioId);
        var swap = ShouldSwapLists(sessionId, scenarioId);

        var assignment = new UserStudyAssignment
        {
            SessionId = sessionId,
            ScenarioId = scenarioId,
            StrategyForListA = swap ? baseline : proposed,
            StrategyForListB = swap ? proposed : baseline,
            ComparisonPair = UserStudyScenarioCatalog.GetComparisonPair(scenarioId),
            CreatedAt = DateTime.UtcNow
        };

        _db.UserStudyAssignments.Add(assignment);
        await _db.SaveChangesAsync(cancellationToken);
        return assignment;
    }

    private List<UserStudyTourItemDTO> RankBlind(
        TourPreferenceQuestionnaireDTO profile,
        Dictionary<int, float> semantic,
        string strategy)
    {
        return _tourRanker
            .RankTours(_catalogStore.Tours.ToList(), profile, semantic, null, strategy)
            .Select(x => MapBlindTour(x.Tour, x.Scoring))
            .ToList();
    }

    private static UserStudyTourItemDTO MapBlindTour(TourCatalogItem tour, TourScoringResult scoring)
    {
        var highlight = scoring.MatchReasons.FirstOrDefault()
            ?? $"Tour tại {tour.City} phù hợp sở thích của bạn.";

        return new UserStudyTourItemDTO
        {
            TourId = tour.Id,
            Name = tour.Name,
            City = tour.City,
            MinPrice = tour.MinPrice,
            DurationDays = tour.DurationDays,
            Highlight = highlight
        };
    }

    private Dictionary<int, float> BuildSemanticScores(TourPreferenceQuestionnaireDTO profile) =>
        _modelRegistry.SearchTours(string.Join(" ", profile.TravelInterests), _catalogStore.Tours.Count)
            .ToDictionary(x => x.TourId, x => x.Score);

    private static bool ShouldSwapLists(string sessionId, int scenarioId) =>
        (string.GetHashCode(sessionId, StringComparison.Ordinal) ^ scenarioId) % 2 != 0;

    private void EnsureReady()
    {
        if (!_catalogStore.IsReady || !_modelRegistry.Status.IsReady)
        {
            throw new InvalidOperationException("AI models and catalog must be ready before user study.");
        }
    }

    private static void ValidateScenarioId(int scenarioId)
    {
        if (scenarioId < 0 || scenarioId >= UserStudyScenarioCatalog.ScenarioCount)
        {
            throw new InvalidOperationException($"ScenarioId must be between 0 and {UserStudyScenarioCatalog.ScenarioCount - 1}.");
        }
    }
}
